docker-compose.yml
CI gives an error when sharing a volume that includes mounted submodules
**Goal**: 
Make build pass
**Changes**:
Extensions in submodules rea now not mounted explicitly anymore.
=> Debug extensions as submodules error

mediawiki/LocalSettings.d/LocalSettings.override.php
For enabling visual editor on private pages
(this template is to be filled out by the person who is creating the pull-request)
**Goal**: 
(bigger goal you want to achieve with this PR)
- Quick fix enabling visual editor on private pages (which are in private namespace) 
- havent tested yet, docs says it should work that way
(these are marked by the person creating the PR and should be checked by the reviewer) 
- Consideration to move that to visualeditor.php
**Note for linking-issue across repositories**:
If the issue is not in the same Repository as the PR. The issue can be referenced with by 
typing the following here in this markdown: 
user/repository#number
i.e: MARDI4NFDI/example_repo#1
=> Tentative fix for visual editor

docker-compose.yml
This will ensure the latest webproxy related fixes are applied
#73
=> Enable watchtower for reverse proxy

docker-compose-dev.yml
**Changes**:
Changed docker-compose-dev so that restart of watchtower can be controlled while developing. Otherwise it always restarts, which is fine for the production environment, but not always what you would need for development.
=> Control restart of watchtower in local dev environment

.github/workflows/main.yml, docker-compose.yml, run_tests.sh
**Changes**:
- backup gets `container_name: mardi-backup`
- container name is modified accordingly in `run_tests.sh`
=> assign container_name mardi-backup to backup container (fixes #117)

docker-compose.yml
There was a recurring problem that environment variables where not passed to the backup container. This was caused by my misconception that cronjobs are bash scripts. Since they are not, they will not read the environment variables at execution time. Several solutions are discussed here: https://www.baeldung.com/linux/load-env-variables-in-cron-job
**Changes**:
- The docker-backup image is updated so that [the start script passes the environment variables to the cronjob](https://github.com/MaRDI4NFDI/docker-backup/commit/81303a2c44546c8f5fdfbe6b1f9bed1f4fa8c36a)
- The entrypoint is set in portal-compose, so that it is called after the environment variables are defined.
=> Moved entrypoint of backup to portal-compose

docker-compose.yml
Backups are currently kept for 100 days. This uses +- 3 GB (will of course increase as the wiki has more data). Since we had problems with disk space, I set the default number of days to keep backups to 30. It is still possible to override this by setting the KEEP_DAYS parameter in the .env file.
**Changes**:
- KEEP_DAYS in docker-compose.yml 
=> Remove backups earlier to save space

README.md
issue #148 
**Changes**:
- add info about traefik to README
- add instructions for local use of traefik to README
note: it would be nice to make the proposed changes in docker-compose-dev.yml instead of docker-compose.yml, but the docker-compose overrides are lacking... it's not possible to replace the labels (or: environments, volumes, etc) defined in one file by the labels defined in the override file (or our dev). cf. https://github.com/docker/compose/issues/3729
=> Traefik readme

mediawiki/LocalSettings.d/Nuke.php
#180 https://github.com/MaRDI4NFDI/docker-wikibase/issues/22
**Changes**:
- disable nuke extension 
**Note**: revert this change when mediawiki dockerhub image was updated to 1.35.6 https://hub.docker.com/_/mediawiki?tab=tags&page=1&name=1.35
=> temporarily disable Nuke extension #180

mediawiki/LocalSettings.d/Nuke.php
mediawiki 1.35.6 was released already, so the Nuke extension can be enabled again
#181 #180 
Note that https://github.com/MaRDI4NFDI/docker-wikibase/pull/24 must be merged and the package be published before this can pass
**Changes**:
- enable Nuke
=> re-enable Nuke extension

grafana/grafana.template.ini
just a tiny fix after alert notification test, delete the unnecessary double quotes around the sender name from the config file
=> delete doublequotes from email cfg

docker-compose.yml, mediawiki/template.env
per https://github.com/MaRDI4NFDI/T5ProjectManagement/issues/68
in combination with https://github.com/MaRDI4NFDI/docker-backup/pull/17
**Changes**:
- introduce new env var `$BACKUP_CRON_ENABLE` to enable/disable automatic backups via crontab (Default: true)
=> introduce env var to toggle automatic backups

docker-compose.yml
fixes https://github.com/MaRDI4NFDI/portal-compose/issues/155
**Changes**:
- watchtower image pull & container updates scheduled for 1AM every day
- now enabled by default for all containers! (unless `labels: com.centurylinklabs.watchtower.enable=false` is specified for a container) -- @physikerwelt is this ok for all containers, also wdqs-* which have the flag `restart: unless-stopped`?
=> schedule watchtower for 1AM every day &enable for all containers

mediawiki/LocalSettings.d/LocalSettings.override.php
While we don't want to allow anonymous accounts, we want to give users permission to create other users.
Request from @lkastner to create accounts for T1 users.
=> Grant createaccount permissions to users

docker-compose.yml, mediawiki/template.env, prometheus/prometheus.template.yml
**Changes**:
- enable watchtower metrics api
- setup prometheus to scrape watchtower @ port 8080
- set API token in .env on production
=> enable watchtower metrics

prometheus/traefik-pass
previously deleted traefik-pass was mistakenly added again here: https://github.com/MaRDI4NFDI/portal-compose/pull/159#discussion_r883406314
this PR deletes it.
ref #232 
=> remove mistakenly added traefik-pass file again

docker-compose.yml, mediawiki/template.env
inside the mardi-backup container on production, the cron pattern created by this line https://github.com/MaRDI4NFDI/docker-backup/blob/f1a62df3ccb7fe21ecc66349cfe15f76e8f064e3/start.sh#L42, includes the single quotes around the cron pattern in $BACKUP_SCHEDULE. (This does not happen in the same container on my local system.)
Solution: delete quotes as they are not required
NOTE: environment file was modified accordlingly
=> replace single by double quotes from backup cron pattern

docker-compose-dev.yml, docker-compose.yml
**Changes**:
- The WIKIBASE_HOST still had to be changed in wdqs-frontend. Otherwise the prefixes wdt & wd are not recognized.
=> Update WIKIBASE_HOST for wdqs-frontend

mediawiki/LocalSettings.d/LocalSettings.override.php
Currently 
https://portal.mardi4nfdi.de/w/index.php?title=Special:MathWikibase&qid=Q8376
shows a bug. However, it should show a special page. This is due to unset properties. After these properties are defined the error should vanish.
=> Define required settings for Math Popups

mediawiki/LocalSettings.d/Skins.php, test/SearchTest.py
**Changes**:
- Fixes the selenium SearchTest.py so that Vue.js components can be detected.
- SearchTest failed because Vector 2022 skin uses Vue components (see
https://github.com/MaRDI4NFDI/portal-compose/issues/284)
- Vector 2022 is again activated in substitution of Timeless.
=> Fix Searchtest and change to Vector skin

docker-compose.yml
try disabling traefik, open goaccess ports directly
=> Test Goaccess w/o traefik routing

docker-compose.yml, goaccess/README.md, goaccess/goaccess.conf, mediawiki/template.env, traefik/traefik.yml
Implements goaccess with static reports and cron, since websocket-based real time html reports could not get to work in time.
for future reference here are my questions on the goaccess issue tracker and in the traefik forum:
https://github.com/allinurl/goaccess/issues/2369
https://community.traefik.io/t/cannot-connect-to-secure-websocket-goaccess/15550
=> fix GoAccess using CRON and static reports

docker-compose.yml, goaccess/README.md, goaccess/goaccess.conf, traefik/logrotate.conf
- setup goaccess to parse traefik logs rather than apache -- this includes not only requests of the web portal, but of all traefik managed services and, importantly, real visitor IPs.
- add logrotation for traefik (today traefik log is 2.4GB) with new image https://github.com/mardi4nfdi/docker-logrotate
#301 
=> goaccess: parse traefik logs

test/test_backup.sh
Previously, only the number of created backup files was reported (x/3), with a test failure if x<3.
Now the test reports in the case x<3, which files were found and which backup type failed (sql, xml or images)
=> improve verbosity of backup test

docker-compose.yml, mediawiki/template.env
**Changes**:
- Pass grafana information (key & host) to backup container, to enable API queries to grafana.
- Add variables also to template.env.
- API queries are then used in docker-backup to backup grafana dashboards (see https://github.com/MaRDI4NFDI/docker-backup/pull/37)
- Related to issue https://github.com/MaRDI4NFDI/portal-compose/issues/313
=> Pass env variables to backup grafana dashboards

docker-compose.yml
When changing the server to mardi02 we will also change the TLD from .de to .org to prepare this transition, we make the TLD configurable via .env file.
=> Make TLD configurable

docker-compose-dev.yml, docker-compose.yml, mediawiki/LocalSettings.d/LocalSettings.override.php, mediawiki/template.env
**Changes**:
- Pass the importer bot credentials and env variables to the importer container.
- Disable edit rate limiting for bots.
- Adapt string limits, so that entities from Wikidata can be imported.
=> Create Importer bot user

mediawiki/LocalSettings.d/LocalSettings.override.php
Temporary fix to deactivate deprecation warnings, before I can find a more permanent solution through $wgDeprecationReleaseLimit
**Changes**:
- Display errors = 0
=> Deactivate warnings

docker-compose-dev.yml
**Changes**:
- Overwrites WIKIBASE_HOST as wikibase.svc for using the Wikibase Query Service (i.e. SPARQL) in development. Otherwise, the production endpoint (portal.mardi4nfdi.de) is used, as defined in portal-compose.yml.
=> Add wikibase.svc host for dev

docker-compose.yml
**Changes**:
- I am experiencing problems when accessing external API endpoints from within docker containers in production. I think this is due to our transfer to OpenStack, since we were already having the same problem in our other VMs.
- This is the solution we used for development (see https://mlohr.com/docker-mtu/ and https://portal.mardi4nfdi.de/wiki/Project:Docker_OpenStackVM)
=> Add mtu value for docker-compose

docker-compose-dev.yml, docker-compose.yml
**Changes**:
- This activates the importer api https://github.com/MaRDI4NFDI/importer-api
- It will enable running the importer scripts (zbmath, arxiv, ...) from outside the production server.
=> Activate importer API

README.md, docker-compose.yml, mediawiki/LocalSettings.d/Wikibase.php
**Changes**:
- This is an attempt to fix https://github.com/MaRDI4NFDI/portal-compose/issues/386 by changing the paths.
- This also fixes a couple of mistakes regarding the env variables in docker-compose.yml
=> Fix GUI statement links

docker-compose.yml, oaipmh/cassandra-env.sh, oaipmh/cassandra.yaml, oaipmh/oaicat.properties
Update fiz oai version, cf, https://github.com/MaRDI4NFDI/fiz-oai-docker/pull/1/files
=> Update oai-pmh version

.github/workflows/main.yml, docker-compose.yml, traefik/conf/stack.yml
=> Test installing stack service

mediawiki/LocalSettings.d/LocalSettings.override.php
cf. https://github.com/MaRDI4NFDI/portal-compose/issues/419
**Changes**:
- 
- 
-  
=> Use Redis as jobqueue

mediawiki/LocalSettings.d/Wikibase.php
Adjust $wgNamespacesToBeSearchedDefault to no longer include wikibase items.
Improves https://github.com/MaRDI4NFDI/MaRDIRoadmap/issues/1
=> Do not search mardi-items by default

docker-compose.yml
inspired by https://stackoverflow.com/a/52434226 which passes the blazegraph options directly according to
https://github.com/wikimedia/wikidata-query-rdf/blob/0922c4c4dead1e4937f3c3b4afeb89eb79bd808d/dist/src/script/runBlazegraph.sh#L144
=> Increase blazegraph timeout to 1h

mediawiki/LocalSettings.d/Wikibase.php
Reverts MaRDI4NFDI/portal-compose#442
The items were still included in the default search. Most likely the problem is that we include the so called "example settings" from Wikibase, here
https://github.com/MaRDI4NFDI/portal-compose/blob/17d65dfc1479695d728f65156da1274ab149b8f0/mediawiki/LocalSettings.d/Wikibase.php#L5C1-L5C67
=> Revert "Do not search mardi-items by default"

my.cnf
It avoids portal 500 problems like
MediaWiki internal error.
Original exception: [80160ebca09a7da5d38eebd3] / Wikimedia\Rdbms\DBConnectionError: Cannot access the database: Too many connections (mysql.svc:3306) Backtrace:
**Changes**:
- Increase max db connections to 1000
=> Increase max db connections

.gitignore, docker-compose.yml, mediawiki/LocalSettings.d/DeleteBatch.php
**Changes**:
- This deletes the TLD variable and uses MARDI_HOST instead in preparation for https://github.com/MaRDI4NFDI/portal-compose/issues/461
- MARDI_HOST will be equal to portal.mardi4nfdi.de in production and staging.mardi4nfdi.org for staging.
- delete DeleteBatch extension (unnecessary)
=> Substitute TLD for MARDI_HOST

.github/workflows/main.yml, docker-compose-ci.yml, docker-compose-dev.yml, docker-compose-extra.yml, docker-compose.yml
**Changes**:
- This lists all the docker images at the top of the file
- Also added a tag to deploy to mardi02
=> List all images at top

docker-compose.yml, mediawiki/LocalSettings.d/Wikibase.php, mediawiki/template.env, wdqs/runUpdate.sh
**Changes**:
- Pull images from https://github.com/MaRDI4NFDI/wikibase-release-pipeline as mentioned in https://github.com/MaRDI4NFDI/portal-compose/issues/451.
- Correct Wikibase.php to fix synchronization in WDQS.
- Overwrite runUpdate.sh in WDQS-updater to include port, which fixes synchronization.
- Add COMPOSE_FILE in template.env to avoid chaining files when doing docker-compose up.
=> Pull wmde images

docker-compose.yml
For some reason the file in the WDQS container is
called whitelist.txt while the service defaults to a file named allowlist.txt
Closes #473
=> Fix issue in WDQS container

my.cnf
The maintenance script nukeNS gets rid of all unnecessary text blobs after deleting the pages. The implementation requires a larger package size as we currently run into https://www.mediawiki.org/wiki/Topic:Wtok4l6ov3jh0dc7
**Changes**:
- 
- 
-  
=> Increase mysql max_allowed_package

docker-compose.yml
**Changes**:
- I think we used the wrong Quickstatements tag for the latest image. The one we added is not available any more (deployment fails in srv-mardi03).
- This just uses the latest image from the wikibase release pipeline.
=> Change quickstatements image

docker-compose-extra.yml, oaipmh/fiz-oai-backend.properties
A fundamental problem with zbMATH and swMATH identifiers is that they don't have a prefix. Therefore the full identifier is not part of the plain rest API result. This caused that a check in the OAI-PMH API failed. To disable this check a new switch has been introduced in version 1.2.11.
See
https://github.com/ER-FIZKarlsruhe/fiz-oai-backend/issues/1
**Changes**:
- 
- 
-  
=> Update oai backend

.github/workflows/main.yml
The test-network was used as a bridge between docker-compose and docker-compose stack. It was introduced in connection with #422
**Changes**:
- 
- 
-  
=> Remove test network

docker-compose.yml
There are now different conflicting mechanisms to pass oauth parameter to qs
* Set the ini file to read only for qs container
* Remove environment varables with oauth params for qs container
cf #502
**Changes**:
- 
- 
-  
=> Use ini file from wikibase to pass oauth param to qs

mediawiki/LocalSettings.d/LocalSettings.override.php
**Changes**:
- Deactivate captchas when adding external URLs to pages, items, etc.
=> Deactivate URL captcha trigger

docker-compose.yml, mediawiki/LocalSettings.d/ExternalData.php, mediawiki/LocalSettings.d/MSC_classification.php
In our last MaRDI meeting we discussed showing the MSC classification labels directly from information stored in the database. Thus avoiding having to insert the MSC label in the knowledge graph. This PR would be a first step towards that.
**Changes**:
- Activate the ExternalData extension and define a query to get the label, once the info is the db.
=> Add MSC classification

docker-compose.yml
When
https://github.com/wmde/wikibase-release-pipeline/pull/625 we have to remove the custom workaround, when we update the wdws version, currently pinned to  ghcr.io/wmde/wikibase/wdqs:7443724965.
**Changes**:
- 
- 
-  
=> Remove allowlist workaround T355893

docker-compose-extra.yml
The oai backend sends out very verbose warnings regarding the elasticsearch configuration. This change suppresses that warning.
sample
```
07:05  INFO: processCrosswalkForItem Zbl34614
2024-07-19 14:36:56.509 WARN  [RestClient] - request [GET http://elasticsearch-oai:9200/items/_doc/Zbl34614] returned 1 warnings: [299 Elasticsearch-7.17.13-2b211dbb8bfdecaf7f5b44d356bdfe54b1050c13 "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security."]
07:05  INFO: Updateing item datestamp 2024-07-19T14:36:56Z
07:05  INFO: processCrosswalkForItem Zbl34615
2024-07-19 14:36:56.518 WARN  [RestClient] - request [GET …
```
=> Disable verbose warnings in oai backend

docker-compose-extra.yml
This PR updates the docker-compose-extra.yml file by stating the fiz-oai-backend is version 1.3.1.
=> bump fiz-oai-backend to 1.3.1

mediawiki/LocalSettings.d/LocalSettings.override.php
Speed up "On high-traffic wikis, this should be set to false, to avoid the need to check the file modification time, and to avoid the performance impact of unnecessary cache invalidations. " see https://www.mediawiki.org/wiki/Manual:$wgInvalidateCacheOnLocalSettingsChange
=> Speed up high-traffic wiki

.github/workflows/main.yml
Some scheduled builds failed due to missing disk space. Thus, we remove tools not required via a solution suggested here https://github.com/orgs/community/discussions/25678#discussioncomment-5242449
=> Reduce image size

docker-compose.yml
Setting query... as an explicit alias creates a DNS entry within dockers internal DNS resolution mechanism.
This leads to the fact that queries won't reach the proxy, but go to the machine directly, which neither listens to HTTPS, nor does it know about their certificate.
=> Fix dns resolution for query.portal.mardi4nfdi.de

mediawiki/LocalSettings.d/LocalSettings.override.php
https://www.mediawiki.org/wiki/Manual:$wgExportFromNamespaces
By default there only is a category selector on Special:Export. This setting also add a namespace selector.
This allows for easy export of all Wikibase properties, or exporting a sample of pages in the Person namespace
=> Add namespace selector to Special:Export

traefik/conf/org-redirect.yml
As discussed in the MaRDI chat
```
Tim Conrad (MaRDI) @tconrad
Moderator
Owner
1:14 PM
Other topic: at the moment this is pointing to our open-stack project: (www.)[mardi4nfdi.org|https://www.mardi4nfdi.org/]
Apparently we are not handling it correctly.
tconrad
It shows "404 page not found"
mschubotz
Moritz Schubotz (MaRDI) @mschubotz
Moderator
Owner
1:18 PM
Das ist de
Nicht org
tconrad
Tim Conrad (MaRDI) @tconrad
Moderator
Owner
1:19 PM
nee - auch die org
mschubotz
Moritz Schubotz (MaRDI) @mschubotz
Moderator
Owner
1:19 PM
Was meinst du mit openstack Projekt
tconrad
Tim Conrad (MaRDI) @tconrad
Moderator
Owner
1:19 PM
Zeigt auf unsere VMs
mschubotz
Moritz Schubotz (MaRDI) @mschubotz
Moderator
Owner
1:20 PM
Wo soll die hinzeigen
Bisher ist .org meiner Meinung nach absichtlich nicht …
```
=> Update org-redirect to new format

README.md
I updated the schubotz-vm to traefik 3.3 and realized the certificates were not renewed. It took me a while to find the appropriate references, so I wanted to document that. After searching, I discovered that this readme is the only place we have traefik documentation.
=> Document traefik problems

mediawiki/LocalSettings.d/OpenID_Connect.php
Currently, we don't rely on attributes provided by the institution. Since most institutions don't offer meaningful attributes like name or email, it is not reasonable to store UIDs generated by the providers.
See https://github.com/MaRDI4NFDI/portal-compose/issues/620
=> Remove unused properties from scope

mediawiki/LocalSettings.d/MathSearch.php, mediawiki/LocalSettings.d/Wikibase.php
Configures max input size of Tex input using new Math extension setting introduced in 
https://github.com/wikimedia/mediawiki-extensions-Math/commit/78b9659e4f7865d580218ece63fcd3f940f7112f
See https://github.com/MaRDI4NFDI/portal-compose/issues/632
=> Math tex max length

docker-compose.yml
**Changes**:
- These additional options in wdqs and in wdqs-updater were not being properly read, resulting in these errors:
```
Error: Could not find or load main class '-Dorg.wikidata.query.rdf.tool.rdf.RdfRepository.timeout=3600'
```
```
Error: Could not find or load main class '-Dorg.wikidata.query.rdf.tool.wikibase.WikibaseRepository.timeout=30000'
```
- Removing the single quotation marks fixes this.
=> remove quotation marks

mediawiki/LocalSettings.d/DisplayTitle.php
Instead of using the regular title, use the displaytitle for ranking.
=> Use display_title for search ranking

docker-compose.yml, mediawiki/LocalSettings.d/DisplayTitle.php
Undo display title overwrite
It fails with the following error
=> Undo display title

mediawiki/LocalSettings.d/LinkedWiki.php
This extension breaks with the latest master branch due to https://phabricator.wikimedia.org/T388624
Disable it for now, as it might not be used anyhow.
=> Temporary disable linkedwiki

mediawiki/LocalSettings.d/LocalSettings.override.php
CLI scripts might take quite long when fetching images from commons
=> Disable instant commons for cli scripts
