MaRDI4NFDI/portal-compose

mediawiki/LocalSettings.override.php
https://www.mediawiki.org/wiki/Wikibase/Installation/Advanced_configuration#Define_links_for_external_identifiers
=> Set formatterUrlProperty

.github/workflows/main.yml, docker-compose.yml
Remove open server ports from main compose file
=> Remove open sever ports

.github/workflows/codeql-analysis.yml
=> Remove js run from codeql

docker-compose.yml
=> Add latexml container with default settings

mediawiki/LocalSettings.d/LocalSettings.override.php
=> Use local latexml instance

.github/workflows/codeql-analysis.yml, .gitignore, docker-compose-dev.yml, docker-compose.yml, run_tests.sh, test/test_backup.sh
**Goal**: 
Backup script should be able to restore the database. For this, the backup service now shares mounts with wikibase. 
**Changes**:
Changed docker-compose.yml (and the other compose files too). Please check at least the docker-compose file.
(these are marked by the person creating the PR and should be checked by the reviewer)
=> PR:  Backup and Restore Test #6 

mediawiki/LocalSettings.d/LocalSettings.override.php
This reverts commit c39858bee4972b96afdbd9973404931c78dd4138.
(this template is to be filled out by the person who is creating the pull-request)
**Goal**: 
(bigger goal you want to achieve with this PR)
- reaching goal xyz (within linked issue 1) 
- reaching goal xyz2 (within linked issue 2) 
- 
**Changes**:
(summary of the basic changes to the source-files within this PR)
- 
- 
-  
(these are marked by the person creating the PR and should be checked by the reviewer) 
**Note for linking-issue across repositories**:
If the issue is not in the same Repository as the PR. The issue can be referenced with by 
typing the following here in this markdown: 
user/repository#number
i.e: MARDI4NFDI/example_repo#1
=> Revert "Allow requests from any origin"

README.md, docker-compose-ci.yml, docker-compose-dev.yml, docker-compose.yml, run_tests.sh
**Goal**: 
Simplify docker-compose-dev.yml
**Changes**:
+ README.md
- docker-compose-dev is completely new https://github.com/MaRDI4NFDI/portal-compose/issues/25
- also merged main into this
(these are marked by the person creating the PR and should be checked by the reviewer)
=> Shrink docker compose dev.yml

test/LaTeXTest.py
**Goal**: 
Added some tests to check if Latexml container is running and if it works.
**Changes**:
Added test file in test dir https://github.com/MaRDI4NFDI/portal-compose/issues/30
Anyway the tests are run on CI and they pass, so there's not much to do.
=> Latex testing

docker-compose.yml
Test https://github.com/MaRDI4NFDI/portal-compose/issues/35#issuecomment-1010252124
=> Use internal name for query frontend

.github/workflows/main.yml, .gitignore, .gitmodules, README.md, docker-compose.yml, mediawiki/LocalSettings.d/LocalSettings.override.php
(this template is to be filled out by the person who is creating the pull-request)
**Goal**: 
(bigger goal you want to achieve with this PR)
- simple image upload 
- private documentation 
- .. in one PR 
**Changes**:
(summary of the basic changes to the source-files within this PR)
- localsettings 
- directory mount for images instead explicit files 
-  
(these are marked by the person creating the PR and should be checked by the reviewer) 
- Check and Approve, this replaces the other PR's 
**Note for linking-issue across repositories**:
If the issue is not in the same Repository as the PR. The issue can be referenced with by 
typing the following here in this markdown: 
user/repository#number
i.e: MARDI4NFDI/example_repo#1
#66 …
=> Private documentation and image upload

docker-compose.yml
watchtower stuff from dke01
(this template is to be filled out by the person who is creating the pull-request)
**Goal**: 
(bigger goal you want to achieve with this PR)
- add watchtower 
**Changes**:
(summary of the basic changes to the source-files within this PR)
- added watchtower 
- 
-  
(these are marked by the person creating the PR and should be checked by the reviewer) 
**Note for linking-issue across repositories**:
If the issue is not in the same Repository as the PR. The issue can be referenced with by 
typing the following here in this markdown: 
user/repository#number
i.e: MARDI4NFDI/example_repo#1
=> Watchtower

test/test_backup.sh
Issue: https://github.com/MaRDI4NFDI/T5ProjectManagement/issues/6
**Changes**:
- New backup image in https://github.com/MaRDI4NFDI/docker-backup
- Here: changed backup test
Check if the backups are actually done on the server by tomorrow
=> Added test for backup of uploaded pictures

.gitmodules, docker-compose.yml, mediawiki/LocalSettings.d/LocalSettings.override.php
**Changes**:
- Twitter timeline can now be embedded 
- Added Extension for twitter timeline 
-  
https://github.com/MaRDI4NFDI/portal-compose/issues/70
=> Twitter timeline

README.md, mediawiki/template.env
**Changes**:
-  removed quotation marks from BACKUP var in .env template
-  removed quotation marks from RESTART var in README
-  
=> remove quotation marks to improve compatibility

docker-compose.yml, mediawiki/LocalSettings.d/Skins.php, mediawiki/template.env
**Changes**:
- Add skin settings for Medik
- ATTENTION: the mardi-wikibase image has to be the new version with the skin pull request from docker-wikibase, otherwise, this will fail as it assumes the Medik skin to be present
-  
=> New Skin settings

README.md
**Changes**:
- Document local development
=> Document local development

.github/workflows/main.yml, mediawiki/LocalSettings.d/EmbedVideo.php
**Changes**:
- add config file for EmbedVideos, requires docker-wikibase pull request to work https://github.com/MaRDI4NFDI/docker-wikibase/pull/8
- 
-  
=> add config file for EmbedVideo

README.md
**Changes**:
- Describe how to do remote debug
=> Remote debug description

.gitignore, extensions-dev/README.md
**Changes**:
- Adding a folder for storing extensions in development
- Same ide view can be used for files and extensions
=> extension-development folder

mediawiki/LocalSettings.d/LocalSettings.override.php, mediawiki/LocalSettings.d/SyntaxHighlight_GeSHi.php
**Changes**:
- add support for syntax highlighting
- 
-  
=> Syntax highlight

docker-compose.yml, run_tests.sh
This avoids that a new volume has to be created for each commit.
Alternative to https://github.com/MaRDI4NFDI/portal-compose/pull/120
Depends on https://github.com/MaRDI4NFDI/docker-wikibase/pull/9 and https://github.com/MaRDI4NFDI/docker-backup/pull/9
**Changes**:
- 
- 
-  
=> Use shared configuration

docker-compose-dev.yml, traefik/traefik.yml
In #134 I forgot to remove the whoami container from docker-compose-dev.yml
**Changes**:
- done now
=> remove whoami from docker-compose-dev.yml, too, #132 #134

test/EmbedVideoTest.py, test/MedikTest.py, test/SyntaxHighlightTest.py
**Changes**:
- added tests for EmbedVideo and SyntaxHighlight extensions as well as Medik Skin
- 
-  
=> tests that extensions and skin are shown in versions page

docker-compose-dev.yml, docker-compose.yml
very minor issue #145 
**Changes**:
- simply disable traefik for the 3 containers which raise missing ports errors
=> disable traefik for containers w/o ports

test/test_backup.sh
Test for [MaRDI4NFDI/docker-backup#12](https://github.com/MaRDI4NFDI/docker-backup/pull/12).
Note that these changes in docker-backup are required for the new test to pass!
**Changes**:
- added test to check if metrics were written during backup
- minor improvement in other test
=> add test for backup metrics, for MaRDI4NFDI/docker-backup#12

docker-compose.yml, mediawiki/LocalSettings.d/LocalSettings.override.php, mediawiki/template.env
**Changes**:
- Formulasearch is now in MaRDI Portal and should be possible with these changes
- Adding formulasearch restapi for basex backend. 
- Adding harvests volume for the index-files created within wikibase
=> Formulasearch portal

docker-compose.yml
=> quick-fix: change restart policy of formulasearch

docker-compose.yml
=> Rollback formulasearch deployment

docker-compose.yml
=> Again doing formulasearch deployment

mediawiki/LocalSettings.d/Slides.php, test/SlidesTest.py
https://github.com/MarDI4NFDI/portal-compose/issues/70
**Changes**:
- Add Slides extension for wikibase
=> Add Slides Extensions and corresponding Test

README.md, grafana/backup_monitor.json
**Changes**:
- add json file of backup monitor
- add instructions in README
=> add json file of backup monitor

mediawiki/LocalSettings.d/VisualEditor.php
https://github.com/MaRDI4NFDI/docker-wikibase/issues/25
**Changes**:
- Correction of the absolute path to the Parsoid extension files, so that they can be found by update.php
=> Update absolute route to properly load Parsoid Extension

mediawiki/LocalSettings.d/EmbedVideo.php, mediawiki/LocalSettings.d/LocalSettings.override.php, mediawiki/LocalSettings.d/YouTube.php, test/ExternalContentTest.py, test/YouTubeTest.py
**Changes**:
- New extension for importing external content in pages. 
=> Feature mirror mediawiki pages

docker-compose.yml
Trivial change. Just learned that docker-compose supports this, slightly less typing ...
merge #215 first -> blocked 
=> Simplify environment variable handling in dockerfile

docker-compose.yml, mediawiki/template.env
**Changes**:
- Added env vars for formulasearch persistency handling. 
https://github.com/MaRDI4NFDI/portal-compose/issues/222
=> Feature api to basex

mediawiki/LocalSettings.d/LocalSettings.override.php
related #190 
**Changes**:
- trivially allow svg files to be uploaded
=> allow file upload of svg files

mediawiki/template.env
**Changes**:
- remove comment from end of line 
=> fix backup_schedule setting

mediawiki/LocalSettings.d/LocalSettings.override.php
**Changes**:
- increase memory limit in LocalSettings.override
closes #237
=> increase memory limit

docker-compose-dev.yml, docker-compose.yml, mediawiki/template.env
**Changes**:
- add docker importer to portal compose
=> add docker importer to portal compose

docker-compose.yml, mediawiki/template.env
**Changes**:
- part of the fix for disabling deprecation warnings in prod 
- just env flag and template here
=> fix deprecation warnings in production 

mediawiki/LocalSettings.d/Skins.php
=> enable Timeless skin and fix MaRDI color of Medik skin

docker-compose-dev.yml
**Changes**:
- add bot env vars to dev docker compose
- 
-  
=> add bot env vars to dev docker compose

mediawiki/LocalSettings.d/Plausible.php
Enable and configure plausible extension, to be used for testing with cloud version of plausible.io (free trial).
#189 https://github.com/MaRDI4NFDI/T5ProjectManagement/issues/126
=> enable plausible extension

docker-compose.yml
**Changes**:
- Assign URL for new swMATH frontend
=> Add swMATH entry point

docker-compose.yml
**Changes**:
- Accept staging.swmath.org as domain
=> Add staging.swmath.org subdomain

docker-compose.yml, goaccess/README.md, goaccess/goaccess.conf, traefik/traefik.yml
use GoAccess.io log analyzer to parse the apache logs and serve them under stats.portal.mardi4nfdi.de
=> GoAccess log analyzer

docker-compose.yml
addendum to #295: expose ports for real time updates via websocket
=> expose port

docker-compose.yml
add traefik SSL cert dumper for goaccess ssl websocket
=> add traefik SSL cert dumper for goaccess ssl websocket

goaccess/README.md
**Changes**:
- update goaccess readme
=> Update goaccess README.md

goaccess/goaccess.conf, traefik/logrotate.conf
=> anonymize ips in goaccess; weekly logrotation

docker-compose.yml
=> fix jaeger auth

docker-compose.yml
**Changes**:
- close jaeger ports, should not be required
=> Jaeger: close ports

docker-compose.yml
Requires local env variables
MATOMO_DATABASE_HOST
MATOMO_DATABASE_ADAPTER
MATOMO_DATABASE_TABLES_PREFIX
MATOMO_DATABASE_USERNAME
MATOMO_DATABASE_PASSWORD
MATOMO_DATABASE_DBNAME
PHP_MEMORY_LIMIT
**Changes**:
- 
- 
-  
=> Setup mamoto service

docker-compose.yml
=> Fix matomo traefik route

docker-compose.yml, mediawiki/LocalSettings.d/PluggableAuth.php, mediawiki/LocalSettings.d/Shibboleth.php, test/test_backup.sh
=> Shibboleth extensions

mediawiki/LocalSettings.d/LocalSettings.override.php
=> Enable instant commons

mediawiki/LocalSettings.d/VisualEditor.php
**Changes**:
- deleting setting up parsoid extension for visual editor, so that it uses default settings
- this fixes save-issues in visual editor (currently fixed this by commenting the lines in production) 
See https://github.com/MaRDI4NFDI/portal-compose/issues/329
=> Fixing visual editor 

docker-compose.yml
Close https://github.com/MaRDI4NFDI/portal-compose/issues/326
**Changes**:
- 
- 
-  
=> Add scholia service

docker-compose.yml, mediawiki/LocalSettings.d/LocalSettings.override.php, mediawiki/LocalSettings.d/VisualEditor.php
**Changes**:
- Close #171 
- Expose wiki mongo publicly
- Configure VE variable to be aware of the wiki mongo instance
=> Fix real-time collaboration extension in production

docker-compose.yml, mediawiki/LocalSettings.d/MatomoAnalytics.php, mediawiki/template.env
**Changes**:
- Update ElasticSearch version in template.env (otherwise local development fails)
- Add variables to template.env to reestablish consistency with the production .env file and avoid warnings in local development.
- Fix typos regarding Matomo analytics
- This is expected to fix the GUI tests
=> Fix failing tests 

.github/workflows/main.yml, docker-compose.yml
**Changes**:
- Change URLs for the importer
- Comment network alias so that runUpdate.sh does not fail. 
=> Fix importer and wdqs urls

docker-compose.yml
**Changes**:
- Correct the environment variable for the sparql endpoint in importer.
- This enables sparql queries through mardi-importer.
=> Correct sparql endpoint for importer

mediawiki/LocalSettings.d/LocalSettings.override.php
**Changes**:
- A higher character limit for the wikibase item descriptions is needed to import PolyDB descriptions.
=> Increase description char limit

mediawiki/LocalSettings.d/LocalSettings.override.php
=> Restore  LocalSettings.override.php

mediawiki/LocalSettings.d/LocalSettings.override.php
**Changes**:
- Increase string limit to 200000
=> Increase string limit for zbMath

docker-compose.yml
cf. https://github.com/MaRDI4NFDI/portal-compose/issues/376
**Changes**:
- 
- 
-  
=> tmp revert to previously running portal version

mediawiki/LocalSettings.d/LocalSettings.override.php
**Changes**:
- Change vector version
=> Revert vector version

docker-compose.yml
=> look for updates on monday at 1 am

test/test_backup.sh
**Changes**:
- Change error code for deleted images from 404 to 403
=> Fix CI Errors

docker-compose-ci.yml, mediawiki/LocalSettings.d/LocalSettings.override.php, mediawiki/LocalSettings.d/Vector.php, mediawiki/LocalSettings.d/Wikibase.php
Removed in https://github.com/MaRDI4NFDI/docker-wikibase/pull/93
**Changes**:
- 
- 
-  
=> Add setings explicitly

mediawiki/LocalSettings.d/LocalSettings.override.php
**Changes**:
- MathML Rendering activation 
=> Enable NativeMathML rendering

docker-compose.yml
=> increase elasticsearch heap size

docker-compose-ci.yml, docker-compose-dev.yml
**Changes**:
- Change heap size for CI and dev environments.
- This should fix the CI
=> Fix heap size CI/dev

mediawiki/LocalSettings.d/mardi_namespaces.php
cf. #392
**Changes**:
- 
- 
-  
=> Create custom mardi namespaces

traefik/traefik.yml
**Changes**:
- Redirect .org traffic to .de
=> Redirect .org domain

mediawiki/LocalSettings.d/CodeEditingExtension.php
This will be applied in both instances
staging.swmath.org as well as
portal.mardi4nfdi.de
=> Enable extensions to edito code

traefik/conf/org-redirect.yml, traefik/traefik.yml
put redirect config into own file
=> Traefik redirects

mediawiki/LocalSettings.d/mardi_namespaces.php
They are defined by the extension
=> Remove extra codemeta namespaces

docker-compose.yml
**Changes**:
- Remove quotation marks
=> Fix sparql endpoint url

docker-compose.yml
=> Install uptime monitor

docker-compose.yml, oaipmh/.cassandra_dump_env, oaipmh/cassandra-env.sh, oaipmh/cassandra.yaml, oaipmh/fiz-oai-backend.properties, oaipmh/init-fizoai-database.sh, oaipmh/init-fizoai-elasticsearch.sh, oaipmh/item_mapping_es_v7, oaipmh/jmxremote.access, oaipmh/jmxremote.password, oaipmh/oai-elasticsearch.yml, oaipmh/oaicat.properties, oaipmh/wait-for-it.sh
Before the services are made available via a public URL, the passwords need to be changed in     
the local config overwrites as described in the [readme](https://github.com/MaRDI4NFDI/fiz-oai-docker/blob/ab7320ad2cfd9870184caf6cef19c86a876acf12/README.md).
=> Add OAI-PMH containers

docker-compose.yml, my-repl.cnf, my.cnf
=> Add mysql replication server

my.cnf
* Avoid binary files beeing corrupted from docker reboots
#413
**Changes**:
- 
- 
-  
=> MySQL set sync_binlog=1

README.md
If I had run these commands on my laptop rather than my PC, I'd have ended up with a frozen OS.
=> Add memory usage warning to the README

.github/workflows/stack.yml, docker-compose-stack.yml
=> Add stack boilerplate

docker-compose-stack.yml
=> Add redis-commander to stack

.github/workflows/stack.yml, docker-compose-stack.yml
=> Add stack test network

docker-compose-stack.yml
=> Add whoami test swarm service

docker-compose-stack.yml
=> Add whoami to test overlay network

traefik/conf/stack.yml
=> Setup who am i test service

mediawiki/LocalSettings.d/00_database.php
=> Use repl db for read queries

mediawiki/LocalSettings.d/MathSearch.php
**Changes**:
- This increases the character limit for MathML expressions in Wikibase
=> increase mathml character limit

mediawiki/LocalSettings.d/MathSearch.php
**Changes**:
- Increase limit to 30000
=> Further increase MathML character limit

mediawiki/LocalSettings.d/SPARQL.php
depends on https://github.com/MaRDI4NFDI/docker-wikibase/pull/110
**Changes**:
- Enables SPARQL extension
depends-on: https://github.com/MaRDI4NFDI/docker-wikibase/pull/110
=> Enable SPARQL extension

docker-compose.yml
=> Revert to last wikibase container

docker-compose.yml, redis-jobrunner-conf.json
**Changes**:
- Installs the redis Jobrunner
- 
-  
=> Redis jobrunner

docker-compose.yml
=> Add new redis jobrunner service

docker-compose.yml, my-repl.cnf
=> Remove MySQL replica

docker-compose.yml
* set up basic auth
* provide access to fiz oai write backend
=> Add proxy to access oai-pmh backend

mediawiki/LocalSettings.d/MatomoAnalytics.php, mediawiki/LocalSettings.d/VisualEditor.php, mediawiki/LocalSettings.d/email.php, mediawiki/template.env, traefik/traefik.yml
**Changes**:
- This just removes some hard-coded portal.mardi4nfdi.de to avoid errors and unexpected behaviors in staging.
=> Remove hard-coded mardi hosts

README.md, docker-compose-dev.yml
**Changes**:
- Update steps to run the development environment.
- Update deployment documentation.
=> Update documentation for dev/deployment

docker-compose-dev.yml, docker-compose-extra.yml, docker-compose.yml
**Changes**:
- Overwrite runUpdate.sh only in the local development environment.
- Change SPARQL endpoint for docker-importer.
=> Fix wdqs configuration for staging and development env

docker-compose-extra.yml, docker-compose.yml, mediawiki/LocalSettings.d/MatomoAnalytics.php, mediawiki/LocalSettings.d/VisualEditor.php, mediawiki/LocalSettings.d/email.php, mediawiki/template.env
**Changes**:
- This uses directly the WIKIBASE_HOST variable, without the extra variable MARDI_HOST.
=> delete MARDI_HOST variable

mediawiki/LocalSettings.d/OpenID_Connect.php, mediawiki/template.env
**Changes**:
- Add NFDI AAI auth
- Can be only tested in production as backlink points to https://portal.mardi4nfdi.de/wiki/Special:PluggableAuthLogin
See also https://github.com/MaRDI4NFDI/MaRDIRoadmap/issues/10 and https://github.com/MaRDI4NFDI/MaRDIRoadmap/issues/4#issuecomment-1588667676
=> Allow NFDI AAI Authentication

docker-compose.yml
Close #472
**Changes**:
- Enables quickstatement for testing in staging environment
- 
-  
=> Test new quickstatements implementation

mediawiki/LocalSettings.d/LocalSettings.override.php, mediawiki/LocalSettings.d/OpenID_Connect.php
**Changes**:
- Allows log-in and account creation via NFDI-AAI account
- Removes google login  
=> Aai basic service

docker-compose.yml
Expose blazegraph ui at a password protected location
Close #495
**Changes**:
- 
- 
-  
=> Add wdqs.portal.mardi4nfdi.de as direct access point for blazegraph

docker-compose.yml
=> Use semver releases for wikibase docker

mediawiki/LocalSettings.d/WikibaseCirrusSearch.php
cf. #432
**Changes**:
- Add searchIndexProperties to allow serarching for DE numbers
=> Add searchIndexProperties to allow serarching for DE numbers

mediawiki/LocalSettings.d/LocalSettings.override.php, mediawiki/LocalSettings.d/mardi_namespaces.php
**Changes**:
- Add dataset namespace
- Add dataset QID map
- See https://github.com/MaRDI4NFDI/portal-compose/issues/511
=> Add dataset namespace

mediawiki/LocalSettings.d/CirrusSearch.php
=> Install extension AdvancedSearch

mediawiki/LocalSettings.d/LocalSettings.override.php, mediawiki/LocalSettings.d/mardi_namespaces.php
**Changes**:
- Add community namespace
- Enable creation of community profile pages with script
=> Add community namespace

docker-compose.yml
=> Update to Wikibase 1.43

mediawiki/LocalSettings.d/LocalSettings.override.php
**Changes**:
- Define $wgMathEnableExperimentalInputFormats
=> Enable experimental inputs formats

docker-compose-extra.yml
See https://github.com/ER-FIZKarlsruhe/fiz-oai-backend/releases/tag/1.3.0
=> Update oai-pmh version

docker-compose-extra.yml
Provide an experimental public TeX to MathML
rendering endpoint at 
https://latexml.portal.mardi4nfdi.de
=> Make MaRDIs LaTeXML service public

docker-compose-ci.yml, docker-compose-extra.yml
Install Machine Learning services for classifying mathematical research data according to the mathematics subject classification MSC
=> Set up 3 MSC related services

mediawiki/LocalSettings.d/LocalSettings.override.php
See https://www.mediawiki.org/wiki/Manual:$wgUseFileCache
=> Speedup for not logged in usesr

mediawiki/LocalSettings.d/LocalSettings.override.php
See https://www.mediawiki.org/wiki/Manual:$wgLocalisationCacheConf and https://www.mediawiki.org/wiki/Manual:$wgCacheDirectory
=> Store language cache on disk

docker-compose-extra.yml
=> Start scholia automatically

mediawiki/LocalSettings.d/WikibaseCirrusSearch.php
to enable haswbstatement search, as per #432 .
**Changes**:
-  Added "P1450", //zbMATH Keywords to WikibaseCirrusSearch.php
=>  Adding "P1450", //zbMATH Keywords to WikibaseCirrusSearch.php

oaipmh/oaicat.properties
Add email and force https
cf . https://github.com/MaRDI4NFDI/python-zbMathRest2Oai/issues/101
=> Adjust OAI configuration

docker-compose.yml
Fix CVEs cf https://github.com/MaRDI4NFDI/portal-compose/issues/396
=> Update to mariadb 10.11

mediawiki/LocalSettings.d/LocalSettings.override.php
Some performance tweaks temorary applied to
the portal during the investigation of the bad edit performance https://phabricator.wikimedia.org/T378762
=> Performane tweaks

docker-compose-extra.yml
Set up a persistent copy of the zbMATH2OAI importer
=> persistent rest api importer

docker-compose.yml
**Changes**:
- Use mongo 6.0 to fix incompatibility errors.
=> Tag mongo to version 6.0

wdqs/allowlist.txt
**Changes**:
- Added https://sparql.dblp.org/sparql to allowlist.txt
=> Add https://sparql.dblp.org/sparql to allowlist.txt

mediawiki/LocalSettings.d/mardi_namespaces.php
**Changes**:
- Add namespaces Service: and Algorithm: based on https://github.com/MaRDI4NFDI/MaRDIRoadmap/issues/48 and https://github.com/MaRDI4NFDI/MaRDIRoadmap/issues/49
=> Add namespaces Algorithm and Service

redis-jobrunner-conf.json
**Changes**:
- Add new for https://github.com/MaRDI4NFDI/portal-compose/issues/594 to custom runners
=> Add NormalizeDoi to our own runners

docker-compose.yml
**Changes**:
- Update to the latest 1.44 wmf branch
=> Update to 1.44 release

redis-jobrunner-conf.json
Temporary workaround for missing RAM
=> Reduce custom jobrunners

docker-compose-extra.yml
=> Setup matomos own SQL server

docker-compose.yml
=> Update MaRIA db version

README.md, docker-compose-ci.yml, docker-compose-dev.yml, docker-compose-extra.yml, docker-compose.yml, mediawiki/LocalSettings.d/Skin.php, mediawiki/LocalSettings.d/widgets.php, redis-jobrunner-conf.json, test/test_backup.sh
In https://github.com/MaRDI4NFDI/docker-wikibase/pull/176 the symlik to `w`
was removed and mediawiki was moved
into the subfolder w of the apache folder.
=> Update core path

mediawiki/LocalSettings.d/UserMerge.php
cf. https://github.com/MaRDI4NFDI/portal-compose/issues/620
=> Enable extension UserMerge

docker-compose-extra.yml, mediawiki/LocalSettings.d/LocalSettings.override.php
cf. https://github.com/MaRDI4NFDI/portal-compose/issues/623
and https://www.mediawiki.org/wiki/Extension:TimedMediaHandler#Shellbox_isolation
=> Set up video rendering container

mediawiki/LocalSettings.d/TimedMediaHandler.php
Enable the extension in a follow-up step
=> Add config for TimedMediaHandler

docker-compose.yml
**Changes**:
- Write DB_SERVER as env variable to be able to change it to connect to the Kubernetes cluster (first just in staging)
=> write DB_SERVER as env variable

docker-compose.yml, mediawiki/WikibaseFacetedSearch.php
cf. https://github.com/MaRDI4NFDI/MaRDIRoadmap/issues/71
depends on 
https://github.com/MaRDI4NFDI/docker-wikibase/issues/185
=> Create WikibaseFacetedSearch.php configuraiton

mediawiki/LocalSettings.d/WikibaseFacetedSearch.php
cf. https://github.com/MaRDI4NFDI/MaRDIRoadmap/issues/71
=> Disable WikibaseFacetedSearch

docker-compose-extra.yml
…/ER-FIZKarlsruhe/fiz-oai-provider/tags
**Updating the composer with the last version of the OAI-provider, which is 1.5.0**
=> Update  OAI-provider

docker-compose.yml
Add url to test en.wiki.staging.mardi4nfdi.org
Remove staging.swmath.org
=> Update wiki URLs

mediawiki/LocalSettings.d/Wikibase.php
cf https://github.com/ProfessionalWiki/WikibaseExport/issues/190
Close #658
=> Temporary disable WikibaseExport
